services:
  mysql:
    image: mysql:8.4
    container_name: mysql-db
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: s3cr3tRoot
      MYSQL_DATABASE: patterncraft_db
      MYSQL_USER: pc_user
      MYSQL_PASSWORD: Str0ngPass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
