"""Add likes model and relationships

Revision ID: 16f0f9017358
Revises: 9169f38b4f02
Create Date: 2025-05-11 17:27:33.120390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f0f9017358'
down_revision = '9169f38b4f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('unique_user_solution_like', ['user_id', 'solution_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_solution_like', type_='unique')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
