"""remove discourse_reply and discourse_reply_vote tables

Revision ID: 180947c11982
Revises: d5a80d3bf539
Create Date: 2025-05-27 01:09:04.480190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '180947c11982'
down_revision = 'd5a80d3bf539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discourse_reply_votes')
    op.drop_table('discourse_replies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discourse_replies',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['discourse_comments.id'], name='discourse_replies_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='discourse_replies_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('discourse_reply_votes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reply_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vote_type', mysql.VARCHAR(length=4), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['reply_id'], ['discourse_replies.id'], name='discourse_reply_votes_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='discourse_reply_votes_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
