"""Add difficulty and stats fields to Problem model

Revision ID: 43ee3b63b137
Revises: 56c498947452
Create Date: 2025-05-25 23:27:12.587900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ee3b63b137'
down_revision = '56c498947452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('author', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('satisfaction_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('votes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('issues', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_column('issues')
        batch_op.drop_column('votes')
        batch_op.drop_column('satisfaction_rating')
        batch_op.drop_column('author')
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
