"""Add is_hidden

Revision ID: 65e6b1cadd4c
Revises: 9ba35af6820a
Create Date: 2025-06-23 01:27:18.807329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e6b1cadd4c'
down_revision = '9ba35af6820a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('theories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theories', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')

    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')

    # ### end Alembic commands ###
