"""add language and status field to problem model

Revision ID: 8616d13977c5
Revises: c43efcf906c1
Create Date: 2025-05-26 19:07:15.212290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8616d13977c5'
down_revision = 'c43efcf906c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
