"""Add likes table

Revision ID: 9169f38b4f02
Revises: b017f6910d69
Create Date: 2025-05-11 17:19:26.732206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9169f38b4f02'
down_revision = 'b017f6910d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', mysql.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('likes')
    # ### end Alembic commands ###
