"""Add new_email field to User model

Revision ID: b017f6910d69
Revises: 031a850ef49c
Create Date: 2025-05-11 15:53:13.000930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b017f6910d69'
down_revision = '031a850ef49c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_email', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['new_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('new_email')

    # ### end Alembic commands ###
