"""Update problem  vote system and satisfaction calculation

Revision ID: bfc973898e26
Revises: daa377546aa9
Create Date: 2025-05-26 15:45:46.305263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfc973898e26'
down_revision = 'daa377546aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('positive_vote', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('negative_vote', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('neutral_vote', sa.Integer(), nullable=True))
        batch_op.drop_column('issues')
        batch_op.drop_column('votes')

    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.drop_column('satisfaction_rating')
        batch_op.drop_column('issues')
        batch_op.drop_column('votes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('issues', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('satisfaction_rating', mysql.FLOAT(), nullable=True))

    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('issues', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('neutral_vote')
        batch_op.drop_column('negative_vote')
        batch_op.drop_column('positive_vote')

    # ### end Alembic commands ###
