"""Change language field to languages list

Revision ID: d4fbc9401094
Revises: fdcc8a4a79c6
Create Date: 2025-05-26 19:32:00.443587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4fbc9401094'
down_revision = 'fdcc8a4a79c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('languages', sa.JSON(), nullable=False))
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('languages')

    # ### end Alembic commands ###
