"""rename languages column to language

Revision ID: d5a80d3bf539
Revises: d4fbc9401094
Create Date: 2025-05-26 19:54:05.564454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5a80d3bf539'
down_revision = 'd4fbc9401094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=False))
        batch_op.drop_column('languages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('languages', mysql.JSON(), nullable=False))
        batch_op.drop_column('language')

    # ### end Alembic commands ###
