"""Add satisfaction_rating and stats fields to Solution model

Revision ID: d89ad90b7b7a
Revises: 43ee3b63b137
Create Date: 2025-05-25 23:27:56.287050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89ad90b7b7a'
down_revision = '43ee3b63b137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('satisfaction_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('votes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('issues', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.drop_column('issues')
        batch_op.drop_column('votes')
        batch_op.drop_column('satisfaction_rating')

    # ### end Alembic commands ###
